[config]
default_to_workspace = false

[tasks.create]
description = "Create a new AtCoder project"
script = [
    "cargo new ${@}",
    "cargo add proconio superslice -p ${@}",
    "rm -f ${@}/src/main.rs",
    "mkdir -p ${@}/src/bin",
    "for i in {a..g}; do cp template.rs \"${@}/src/bin/$i.rs\"; done"
]
